// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQC3c-ZjNbFBZORDBDBHxYEzmA_Bp16Ik',
    appId: '1:943516634106:web:2b64615e5bff2a54d67243',
    messagingSenderId: '943516634106',
    projectId: 'menumia-f10d8',
    authDomain: 'menumia-f10d8.firebaseapp.com',
    databaseURL: 'https://menumia-f10d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'menumia-f10d8.firebasestorage.app',
    measurementId: 'G-F7SC0W7WYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwQo33b6MHmUDoRCBAhm3E1aH28cXCO5I',
    appId: '1:943516634106:android:67410cf49c482916d67243',
    messagingSenderId: '943516634106',
    projectId: 'menumia-f10d8',
    databaseURL: 'https://menumia-f10d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'menumia-f10d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCR6A-hrwuF8R9HYFmvhtdcmqcitgM9XQ',
    appId: '1:943516634106:ios:2f8cb96bd425f19ed67243',
    messagingSenderId: '943516634106',
    projectId: 'menumia-f10d8',
    databaseURL: 'https://menumia-f10d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'menumia-f10d8.firebasestorage.app',
    iosClientId: '943516634106-dbv2v0pctjq6rvmadrsrko4kthvdbjoh.apps.googleusercontent.com',
    iosBundleId: 'com.menumia.partner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCR6A-hrwuF8R9HYFmvhtdcmqcitgM9XQ',
    appId: '1:943516634106:ios:6126ad9880260bcdd67243',
    messagingSenderId: '943516634106',
    projectId: 'menumia-f10d8',
    databaseURL: 'https://menumia-f10d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'menumia-f10d8.firebasestorage.app',
    iosClientId: '943516634106-2lcn16h4otb5c39bua50q43pulriarjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.menumiaFlutterPartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQC3c-ZjNbFBZORDBDBHxYEzmA_Bp16Ik',
    appId: '1:943516634106:web:3e2b0321005e4dbdd67243',
    messagingSenderId: '943516634106',
    projectId: 'menumia-f10d8',
    authDomain: 'menumia-f10d8.firebaseapp.com',
    databaseURL: 'https://menumia-f10d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'menumia-f10d8.firebasestorage.app',
    measurementId: 'G-31X82LXW23',
  );

}